// <auto-generated />
namespace EIRA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Update_QuestionsEntity_AddQuestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_QuestionsEntity_AddQuestion));
        
        string IMigrationMetadata.Id
        {
            get { return "202005221021083_Update_QuestionsEntity_AddQuestion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
