// <auto-generated />
namespace EIRA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Upadte_QuestionEntity_addHasAnswer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Upadte_QuestionEntity_addHasAnswer));
        
        string IMigrationMetadata.Id
        {
            get { return "202005270330576_Upadte_QuestionEntity_addHasAnswer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
